### ISSUE TITLE
User Register Confirmation Email & Token Generation

### ISSUE THREAD

**Issue by wcAlex** [biz2013/xwjy#36]
>> Token Generation
>> Implement Email Confirmation after user registration. 
>> Email will be username
>> error message is Chinese

**Comment by wcAlex** [comment]
@biz2013 

Get an error when calling accountinfo from user registration confirm token, since there is no wallet for the new created user. 
At this line: https://github.com/biz2013/xwjy/blob/master/test1/controller/useraccountinfomanager.py#L263 

Do we need to create wallet for each new confirmed user first? what do you think?

=== Sample Registration Email ==============
Hi test,
Please click on the link to confirm your registration,
http://127.0.0.1:8000/activate/Ng/4su-4fa3afe5e048d3218ea3/

=== Error Message after click above link =======
-------------------------------------------------------------------------------
2018-01-14 19:35:57,706 homeview site.homepage 27679 140460773328640 INFO visit home...
2018-01-14 19:35:57,732 useraccountinfomanager site.useraccountinfomanager 27679 140461012801280 INFO get account info for user test in AXFund
2018-01-14 19:35:57,735 accountinfoview site.accountinfo 27679 140461012801280 ERROR 用户主页显示遇到错误: <class 'users.models.DoesNotExist'>
Traceback (most recent call last):
  File "/home/chi/workspace/python/projects/xwjy/test1/views/accountinfoview.py", line 26, in accountinfo
    useraccountInfo = useraccountinfomanager.get_user_accountInfo(request.user,'AXFund')
  File "/home/chi/workspace/python/projects/xwjy/test1/controller/useraccountinfomanager.py", line 263, in get_user_accountInfo
    userwallet = UserWallet.objects.get(user=user, wallet__cryptocurrency__currency_code=crypto)
  File "/home/chi/workspace/python/envs2/axfundTrading/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chi/workspace/python/envs2/axfundTrading/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: UserWallet matching query does not exist.

**Comment by biz2013** [comment]
I believe this is done

**Comment by biz2013** [comment]
@wcAlex
